### ISSUE TITLE
notifications should be displayed in users currency

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#84]
Notifications should be shown in the display currency set on the users setting screen.

Currently the notification only shows "USD Transaction"

**Comment by brh28** [comment]
The display currency is stored in the accounts table which we're already fetching on payment receive, so nothing new there. However, we'd also need to do a currency conversion. I assume this is already being done elsewhere in the code so shouldn't be tough but would just need to find how its done. 

My bigger concern is whether we actually want to remove the dollar amount, since that is the asset the user is actually receiving. What I would suggest is we add the displayCurrency in parenthesis. For example,
`+ $1.00 (~ J$157.21)`

**Comment by brh28** [comment]
The current code is using the [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) to display the currency, which produces a `$` for JMD rather than `J$` as shown elsewhere in the application. For example:

![Image](https://github.com/user-attachments/assets/c7a07bb8-6e68-457e-9f11-54c444447be3)

@Nodirbek75 Can you share how flash-mobile is rendering the display currency?

**Comment by Nodirbek75** [comment]
@brh28 It's not using any libraries. It converts the USD balance using the real-time price, fetches the currency list, and gets the correct symbol according to the current display currency.

**Comment by brh28** [comment]
> @brh28 It's not using any libraries. It converts the USD balance using the real-time price, fetches the currency list, and gets the correct symbol according to the current display currency.
> 

Could you provide a link to where this done? Specifically, I'm interested how the UI gets the currency symbol

**Comment by Nodirbek75** [comment]
> > @brh28 It's not using any libraries. It converts the USD balance using the real-time price, fetches the currency list, and gets the correct symbol according to the current display currency.
> 
> Could you provide a link to where this done? Specifically, I'm interested how the UI gets the currency symbol

his is the file and the method that is being called:
https://github.com/lnflash/flash-mobile/blob/6f500537ea8a286d07060b796d38a251b557e990/app/hooks/use-display-currency.ts#L319

**Comment by brh28** [comment]
Thanks @Nodirbek75. Digging into this code, I see the symbol is pulled from the `currencyList` graphql query:
```
export const CurrencyListDocument = gql`
  query currencyList {
    currencyList {
      __typename
      id
      flag
      name
      symbol
      fractionDigits
    }
  }
```
The resolver for this query in turn calls the `ListCurrencies` method on the realtime price server

**Comment by islandbitcoin** [comment]
what if we didnt mimic it, and instead got the currency code (JMD or CYD, etc) without the price server?

**Comment by brh28** [comment]
> what if we didnt mimic it, and instead got the currency code (JMD or CYD, etc) without the price server?

Yeah, definitely easier than fetching the currency symbol. To do that, we could copy the format function and then remove/replace the `symbol` with the currency code (e.g "JMD"). I'll test it out and follow up
